name: Cache win64_vc15

on:
  workflow_dispatch:

jobs:
  setup-libs:
    runs-on: windows-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Restore win64_vc15 Cache
        uses: actions/cache@v4
        id: cache
        with:
          path: ../lib/win64_vc15
          key: win64-vc15-cache

      - name: Install SVN
        if: steps.cache.outputs.cache-hit != 'true'
        run: choco install svn -y

      - name: Checkout Blender Libraries
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir ..\lib
          cd ..\lib
          svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/win64_vc15

      - name: Confirm Python Exists
        run: |
          if exist ../lib/win64_vc15/python/310/bin/python.exe (
            echo Python found
          ) else (
            echo Python NOT found && exit 1
          )
