name: Build Goo Engine

on:
  workflow_dispatch:  # manual trigger

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        path: goo-engine-git\goo-engine

    - name: Change Directory
      shell: cmd
      run: |
        cd goo-engine-git\goo-engine

    - name: Restore cache for windows_x64 libs
      id: cache-win64
      uses: actions/cache@v4
      with:
        path: lib/windows_x64
        key: windows_x64-cache
        restore-keys: |
          windows_x64-cache
          
    - name: Download and extract libs if cache miss
      if: steps.cache-win64.outputs.cache-hit != 'true'
      run: |
        curl -L -o windows_x64.7z https://github.com/rPhase/blender-lib-windows_x64/releases/download/v0.0.2/windows_x64.7z
        run: 7z x windows_x64.7z -olib -y
        
    - name: Try update
      shell: cmd
      run: make update
    
    - name: Build Goo Engine (Release)
      shell: cmd
      run: make

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: goo-engine-windows_x64
        path: build_windows_x64_vc17_Release/bin/Release/
